EXEC = python3.13
MOSAICO = mosaico_cs.py
CAMINHO_NOTINHA = /home/usuario/imagens/...
SELECAO = 4 # 1 - ERCS ; 2 - SCS ; 3 - ERCSF ; 4 SCSF
TAMANHO_DO_SALTO = 2










run :
	MOSAICO_PATH=$(CAMINHO_NOTINHA) $(EXEC) mosaico_cs.py
	MOSAICO_ALGORISM=$(SELECAO) $(EXEC) mosaico_cs.py
	MOSAICO_SALTO=$(TAMANHO_DO_SALTO) $(EXEC) mosaico_cs.py
	$(EXEC) $(MOSAICO)